name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mindgains
  GCR_HOSTNAME: gcr.io
  IMAGE_NAME: mindgains-discord-scrapter
  GITOPS_REPO: "mindgains/mindgains-gitops"
  DEPLOYMENT_FILE: "environment/prod/mindgains-discord-scraper/deployment/manifest.yaml"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure Docker to use GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker $GCR_HOSTNAME

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t $GCR_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} .

      # Push Docker image to GCR
      - name: Push Docker Image
        run: |
          docker push $GCR_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}

      # Push "latest" tag
      - name: Tag and Push Latest
        run: |
          docker tag $GCR_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} $GCR_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:latest
          docker push $GCR_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:latest

  update-gitops:
    name: Update GitOps Repository
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Checkout the GitOps repository
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}  # Add a GitHub PAT to push changes

      # Update the deployment file with the new image tag
      - name: Update Image in Deployment File
        run: |
          sed -i "s|image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:.*|image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" ${{ env.DEPLOYMENT_FILE }}

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.email "mindgains-action@github.com"
          git config --global user.name "MindGains Action"
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update deployment image to ${{ github.sha }}"
          git push origin main
